#应用配置
spring:
  application:
    name: security-demo
  zipkin:
    sender:
      #使用http方式发送统计数据 支持RABBIT KAFKA WEB(http)
      type: web
    #可以使用url或者注册中心的serviceId
    base-url: http://common-service/
    #使用服务发现
    discoveryClientEnabled: true
  sleuth:
    sampler:
      #1表示全量采集，默认0.1表示采集10%
      probability: 1
  boot:
    admin:
      client:
        #监控周期
        period: 2000
  #redis config
  redis:
    port: 6379
    password: tv84mApa
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
    database: 1
    host: dev-redis.joinboom.net
#内置tomcat配置
server:
  port: 7211
#注册中心配置
eureka:
  instance:
    hostname: security-test.joinboom.net
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    lease-renewal-interval-in-seconds: 1
    #eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    lease-expiration-duration-in-seconds: 3
    health-check-url-path: /monitor/health
    status-page-url-path: /monitor/info
    metadata-map:
      #cluster设置可以配合turbine进行分组监控
      cluster: test
      management.context-path: /monitor
  client:
    loginUser:
      - eureka1
      - eureka2
    loginPassword:
      - eureka1
      - eureka2
    service-url:
      defaultZone: http://${eureka.client.loginUser[0]}:${eureka.client.loginPassword[0]}@eureka-test1.joinboom.net:7201/eureka,http://${eureka.client.loginUser[1]}:${eureka.client.loginPassword[1]}@eureka-test2.joinboom.net:7202/eureka
    #初始化实例信息到eureka服务端的间隔时间，默认为40秒
    initial-instance-info-replication-interval-seconds: 1
    #询问eureka服务url信息变化的时间间隔（s），默认为300秒
    eurekaServiceUrlPollIntervalSeconds: 60
    #更新实例信息的变化到eureka服务端的间隔时间
    instance-info-replication-interval-seconds: 1
    #从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    registry-fetch-interval-seconds: 1

#附加的监控端点
management:
  server:
    port: 8211
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  endpoint:
    health:
      show-details: always
#日志打印
logging:
  level:
    root: info
    com.wy: debug
    org.springframework.cloud.netflix: debug
    org.springframework.web: info
##自定义参数
jwt:
  tokenHeader: Authorization
  tokenPrefix: "Bearer "
  #token失效时间（不是refreshToken）(s)暂时无用，后续如果需要开启再使用
  expirationSeconds: 300
  #默认8小时登录有效(根据业务更改)（s）
  validTime: 28800
  secret:
    #随机秘钥过期时间（s）
    expire: 10