#zuul
#应用配置
spring:
  application:
    name: producer-gateway-service
#内置tomcat配置
server:
  port: 7205
#注册中心配置
eureka:
  instance:
    hostname: gateway-test.wangtoye.net
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    lease-expiration-duration-in-seconds: 3
  client:
    service-url:
      defaultZone: http://eureka-test1.wangtoye.net:7201/eureka,http://eureka-test2.wangtoye.net:7202/eureka
    #初始化实例信息到Eureka服务端的间隔时间，默认为40秒
    initial-instance-info-replication-interval-seconds: 1
    #更新实例信息的变化到Eureka服务端的间隔时间
    instance-info-replication-interval-seconds: 1
    #从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    registry-fetch-interval-seconds: 1
#熔断配置
hystrix:
  command:
    default: #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,timeoutInMilliseconds无效;
          #为true,则优先查看ribbon的超时时间，小于timeoutInMilliseconds则以ribbon为准，大于则以timeoutInMilliseconds为准。
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms。timeout.enabled为true生效
ribbon:
  ReadTimeout: 2000 #ribbon单次请求超时时间，总超时时间=ReadTimeout*（1+MaxAutoRetries），且总时间小于等于熔断超时时间。
  ConnectTimeout: 3000 #连接超时时间
  MaxAutoRetries: 0 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用,如果只有一个实例，此处效果等同于MaxAutoRetries
  OkToRetryOnAllOperations: true  #是否所有操作都重试 默认GET重试
  eager-load:
    enabled: true #开启饥饿加载机制，防止每个服务第一次ribbon调用时间过长
    clients: producer-service #需要开启饥饿加载机制的服务
#zuul网关配置
zuul:
  debug:
    request: true
  ribbonIsolationStrategy: thread
  ignored-services: "*"
  #路由配置
  routes:
    #    oauth-service:    #认证服务
    #      path: /auth/** #响应的路径
    #      serviceId: oauth-service
    #      stripPrefix: true #去掉前置地址，此处为auth
    #      #springcloud经过zuul转发请求后发生session失效问题，这是由于zuul默认会丢弃原来的session并生成新的session
    #      sensitiveHeaders: true
    producer-service: #生产者服务
      #响应的路径
      path: /producer/**
      serviceId:  producer-service
      stripPrefix: true #去掉前置地址，此处为producer
      sensitiveHeaders: true
  host:
    socket-timeout-millis: 2000 #通过host访问地址的访问超时时间
    connect-timeout-millis: 2000 #通过host访问地址的连接超时时间
#附加的监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
#oauth认证配置
security:
  oauth2:
    client:
      access-token-uri: http://oauth-test.wangtoye.net:7206/uaa/oauth/token #令牌端点
      user-authorization-uri: http://oauth-test.wangtoye.net:7206/uaa/oauth/authorize #授权端点
      client-id: producer-gateway-service #OAuth2客户端ID
      client-secret: 123456 #OAuth2客户端密钥
    resource:
      #      token-info-uri: http://oauth-test.wangtoye.net:7206/oauth/check_token # 验证token的接口
      #      user-info-uri: http://oauth-test.wangtoye.net:7206/user # 一个可以获取认证授权的自定义接口，可以在授权服务器，也可以在其他服务器上
      #      prefer-token-info: false # 如果同时配置了token-info-uri 和 user-info-uri，这个现象设置使用哪个取验证授权
      jwt:
        key-value: wangye10 #使用对称加密方式，默认算法为HS256
#日志配置
logging:
  level:
    root: info
    com.wy: debug
    org.springframework.cloud.netflix: debug
    org.springframework.web: trace
    org.springframework.cloud.netflix.zuul: trace