#应用配置
spring:
  security:
    user:
      name: eureka1
      password: eureka1
#内置tomcat配置
server:
  port: 7201
#注册中心配置
eureka:
  datacenter: nanjing
  environment: dev
  instance:
    hostname: eureka-test1.joinboom.net
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    lease-expiration-duration-in-seconds: 3
    health-check-url-path: /monitor/health
    status-page-url-path: /monitor/info
    metadata-map:
      #本服务的metadata信息，提交到服务端
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
      management.context-path: /monitor
  client:
    loginUser:
      - eureka2
    loginPassword:
      - eureka2
    service-url:
      defaultZone: http://${eureka.client.loginUser[0]}:${eureka.client.loginPassword[0]}@eureka-test2.joinboom.net:7202/eureka
      #初始化实例信息到Eureka服务端的间隔时间，默认为40秒
      initial-instance-info-replication-interval-seconds: 1
      #询问Eureka服务url信息变化的时间间隔（s），默认为300秒
      eurekaServiceUrlPollIntervalSeconds: 60
      #更新实例信息的变化到Eureka服务端的间隔时间
      instance-info-replication-interval-seconds: 1
      #从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
      registry-fetch-interval-seconds: 1
  server:
    #关闭自我保护
    #    enable-self-preservation: false
    #5秒扫描一次客户端，剔除失效服务
    evictionIntervalTimerInMs: 5000
#附加的监控端点
management:
  server:
    port: 8201
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  endpoint:
    health:
      show-details: always
#日志打印
logging:
  file:
  level:
    root: info
    com.wy: debug